# Generated by Django 3.0.4 on 2020-11-05 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Variedad de servicios')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tiposservicio_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tiposservicio_updated', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'db_table': 'TipoServicio',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ordenes.TiposServicio'),
            preserve_default=False,
        ),
    ]
