# Generated by Django 3.0.4 on 2020-11-06 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0003_auto_20201105_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='no_servico',
            new_name='no_servicio',
        ),
        migrations.CreateModel(
            name='HistorialOrdenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.TiposServicio')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.Servicio')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de servicio',
                'verbose_name_plural': 'Historial de servicios',
                'db_table': 'historial_servicio',
            },
        ),
    ]
