# Generated by Django 3.0.4 on 2020-11-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20201106_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=250, verbose_name='Dirección'),
            preserve_default=False,
        ),
    ]
