# Generated by Django 3.0.4 on 2020-11-07 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0004_cliente_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('observacion', models.TextField(verbose_name='Descripcion del servicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.Cliente')),
                ('no_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.Servicio')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_formularservicio_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_formularservicio_updated', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario de Servicio',
                'verbose_name_plural': 'Formulario de Servicios',
                'db_table': 'formulario_servicio',
            },
        ),
    ]
